-- SQLPlus settings for script execution
SET ECHO OFF
SET FEEDBACK ON
WHENEVER SQLERROR CONTINUE

-- Drop tables if they exist
DROP TABLE credits PURGE;
DROP TABLE movies PURGE;

-- Now stop on errors for table creation
WHENEVER SQLERROR EXIT FAILURE

-- Create movies table
CREATE TABLE movies (
    budget NUMBER,
    genres CLOB,
    homepage VARCHAR2(500),
    id NUMBER PRIMARY KEY,
    keywords CLOB,
    original_language VARCHAR2(10),
    original_title VARCHAR2(500),
    overview CLOB,
    popularity NUMBER,
    production_companies CLOB,
    production_countries CLOB,
    release_date DATE,
    revenue NUMBER,
    runtime NUMBER,
    spoken_languages CLOB,
    status VARCHAR2(50),
    tagline VARCHAR2(500),
    title VARCHAR2(500),
    vote_average NUMBER,
    vote_count NUMBER
);

-- Create credits table
CREATE TABLE credits (
    movie_id NUMBER PRIMARY KEY,
    title VARCHAR2(500),
    cast CLOB,
    crew CLOB,
    CONSTRAINT fk_credits_movie FOREIGN KEY (movie_id) REFERENCES movies(id)
);

-- Create indexes for better performance
CREATE INDEX idx_movies_title ON movies(title);
CREATE INDEX idx_movies_release_date ON movies(release_date);
CREATE INDEX idx_movies_vote_average ON movies(vote_average);

-- Add table comments
COMMENT ON TABLE movies IS 'TMDB movies information including budget, revenue, and metadata';
COMMENT ON TABLE credits IS 'Cast and crew information for movies';

-- Add column comments
COMMENT ON COLUMN movies.id IS 'Unique movie identifier';
COMMENT ON COLUMN movies.budget IS 'Movie production budget in dollars';
COMMENT ON COLUMN movies.revenue IS 'Total revenue generated by the movie';
COMMENT ON COLUMN movies.genres IS 'JSON array of movie genres';
COMMENT ON COLUMN movies.keywords IS 'JSON array of movie keywords';
COMMENT ON COLUMN credits.cast IS 'JSON array of cast members';
COMMENT ON COLUMN credits.crew IS 'JSON array of crew members';

COMMIT;

-- Exit successfully
EXIT;
